# Site settings
title: Portfolio
email: elfi_8@mail.ru
description: >
  Freelance web developer, specialising in Jekyll, HTML, CSS and Javascript.
baseurl: "/portfolio"
url: "http://komaschuk.github.io"

linkedin_username: komaschuk
twitter_username: komaschuk
github_username: komaschuk

# permalink: /:categories/:title
links:
  - title: about
    url: about
  - title: work
    url: work
  - title: articles
    url: articles
  - title: hire me
    url: hire-me

# Build settings
baseurl: ''
exclude: ['README.md', 'node_modules', 'gulpfile.js', 'package.json', 'CNAME']