# Site settings
title: Portfolio
email: elfi_8@mail.ru
description: > # this means to ignore newlines until "baseurl:"
  Freelance web developer, specialising in Jekyll, HTML, CSS and Javascript.
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "http://komaschuk.github.io" # the base hostname & protocol for your site

linkedin_username: komaschuk
twitter_username: komaschuk
github_username: komaschuk


permalink: /:categories/:title

links:
  - title: about
    url: about
  - title: work
    url: work
  - title: articles
    url: articles
  - title: hire me
    url: hire-me

# Build settings
markdown: kramdown
exclude: ['README.md', 'node_modules', 'gulpfile.js', 'package.json']